server:
  port: 8989

spring:
  datasource:
    url: jdbc:mariadb://localhost:3316/tek
    username: myadmin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  main:
    allow-circular-references: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
